### ISSUE TITLE
Not compatible with Angular 12 (@angular/cdk@12.1.0)

### ISSUE THREAD

**Issue by amitbarik167** [windmichael/ngx-acuw#8]
Getting error while installing, even force does n't work

![image](https://user-images.githubusercontent.com/28583117/123901685-a419b700-d928-11eb-9994-6d7fe47952c3.png)

**Comment by windmichael** [comment]
This issue should be fixed with 4e9e80e7fdf0b0183e74a627946c819b88bd6eb5.
Please install ngx-acuw@1.4.3

**Comment by amitbarik167** [comment]
It didn't resolve the issue, still some issue with three.js dependency
![image](https://user-images.githubusercontent.com/28583117/124223877-d4e12400-dac1-11eb-842d-cf01bda66a35.png)

**Comment by windmichael** [comment]
The ngx-acuw library has as peerDependency the library "three" with the version 0.126.1 and the library "@types/three" with the verision 0.126.2 defined. 
Please install "three@0.126.1" and "@types/three@0.126.2" via npm on you Angular application. 
This should solve you issue.

**Comment by windmichael** [comment]
The installation instruction has been updated, which prevents the described issue.
